name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: recipes
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: SuperVeiligWachtwoord123!
          MYSQL_ROOT_PASSWORD: rootSuperSecure!
        ports:
          - 3306:3306
        options: >-
          --default-authentication-plugin=mysql_native_password
          --ssl=0

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql

      - name: Copy .env
        run: cp .env.example .env

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h127.0.0.1 -ularavel_user -pSuperVeiligWachtwoord123! --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: recipes
          DB_USERNAME: laravel_user
          DB_PASSWORD: SuperVeiligWachtwoord123!
        run: php artisan migrate --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: recipes
          DB_USERNAME: laravel_user
          DB_PASSWORD: SuperVeiligWachtwoord123!
        run: php artisan test
