name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: recipes
          MYSQL_ROOT_PASSWORD: root   # Fixed password for service only
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHP Linter
        run: |
          vendor/bin/phpcs app/ routes/
          vendor/bin/phpstan analyse app/ --level max

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: recipes
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}   # Secret used only in steps
        run: php artisan migrate --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: recipes
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}   # Secret used only in steps
        run: php artisan test
