name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: recipes
          MYSQL_ROOT_PASSWORD: rootpassword   # tijdelijk, komt overeen met secret
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Haal code uit repository
      - uses: actions/checkout@v4

      # 2. PHP installeren
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      # 3. Composer dependencies installeren
      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # 4. PHP Linter (optioneel)
      - name: Run PHP Linter
        run: |
          if [ -f vendor/bin/phpcs ]; then
            vendor/bin/phpcs app/ routes/
          fi
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse app/ --level max
          fi

      # 5. Kopieer .env voorbeeld en voeg secrets toe
      - name: Setup .env
        run: |
          cp .env.example .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env

      # 6. Maak storage en cache schrijfbaar
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # 7. Wacht tot MySQL beschikbaar is
      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h127.0.0.1 -uroot -p${{ secrets.DB_PASSWORD }} --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      # 8. Voer migraties uit
      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: recipes
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force

      # 9. Voer tests uit
      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: recipes
          DB_USERNAME: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan test
